import Head from "next/head";
import React from "react";

const Seo = () => {
  return (
    <Head>
      <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      <meta name="description" content="Generated by create next app" />
      <meta name="keywords" content="next, app, create next app" />
      <meta name="author" content="create next app" />
      <link rel="icon" href="/favicon.ico" />
      <title>Next Js</title>
    </Head>
  );
};

export default Seo;
